/**
 * Tiny dependency-free PDF writer (Helvetica, US Letter) for tabular reports.
 * Produces real, valid PDF files so the "Export PDF" action works offline.
 */
const W = 612;
const H = 792;
const M = 48;

const REPLACEMENTS = {
  '—': '-',
  '–': '-',
  '’': "'",
  '‘': "'",
  '“': '"',
  '”': '"',
  '•': '-',
  '·': '-',
  '−': '-',
  '…': '...',
};

const esc = (s) =>
  String(s ?? '')
    .replace(/[—–’‘“”•·−…]/g, (c) => REPLACEMENTS[c])
    .replace(/[^\x20-\x7E]/g, '?')
    .replace(/([\\()])/g, '\\$1');

const fit = (text, width, size) => {
  const max = Math.max(3, Math.floor(width / (size * 0.5)));
  const s = String(text ?? '');
  return s.length > max ? `${s.slice(0, max - 3)}...` : s;
};

/**
 * @param {{ title: string, subtitle?: string, columns: {header: string, value: (row:any)=>any, width?: number}[], rows: any[], footer?: string }} spec
 * @returns {Blob}
 */
export function buildPdf({
  title,
  subtitle = '',
  columns,
  rows,
  footer = 'Generated by Sales Dashboard IG',
}) {
  const usable = W - 2 * M;
  const totalWeight = columns.reduce((s, c) => s + (c.width || 1), 0);
  const widths = columns.map((c) => (usable * (c.width || 1)) / totalWeight);
  const xs = widths.reduce((acc, _w, i) => [...acc, i === 0 ? M : acc[i - 1] + widths[i - 1]], []);

  const text = (x, y, s, size = 9, bold = false, gray = 0.15) =>
    `${gray} g BT /${bold ? 'F2' : 'F1'} ${size} Tf ${x.toFixed(1)} ${y.toFixed(1)} Td (${esc(s)}) Tj ET`;

  const pages = [];
  let ops = [];
  let y = 0;

  const header = () => {
    ops.push(`0.95 g ${M} ${y - 6} ${usable} 20 re f`);
    columns.forEach((c, i) =>
      ops.push(text(xs[i] + 6, y, fit(c.header, widths[i] - 8, 8.5), 8.5, true, 0.25)),
    );
    y -= 22;
  };
  const newPage = (first) => {
    if (ops.length) pages.push(ops);
    ops = [];
    y = H - M;
    if (first) {
      ops.push(text(M, y - 14, title, 20, true, 0.08));
      y -= 34;
      if (subtitle) ops.push(text(M, y, subtitle, 10, false, 0.42));
      y -= 30;
    }
    header();
  };

  newPage(true);
  rows.forEach((row, ri) => {
    if (y < M + 30) newPage(false);
    if (ri % 2 === 1) ops.push(`0.985 g ${M} ${y - 6} ${usable} 20 re f`);
    columns.forEach((c, i) => ops.push(text(xs[i] + 6, y, fit(c.value(row), widths[i] - 8, 9), 9)));
    y -= 20;
  });
  pages.push(ops);

  const total = pages.length;
  const objects = [];
  objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';
  objects[3] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>';
  objects[4] =
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>';
  const kids = [];
  pages.forEach((pageOps, i) => {
    const pageId = 5 + i * 2;
    const contentId = pageId + 1;
    kids.push(`${pageId} 0 R`);
    const pageFooter = text(M, 26, `${footer}  -  Page ${i + 1} of ${total}`, 8, false, 0.5);
    const stream = [...pageOps, pageFooter].join('\n');
    objects[pageId] =
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${W} ${H}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentId} 0 R >>`;
    objects[contentId] = `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`;
  });
  objects[2] = `<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${total} >>`;

  let out = '%PDF-1.4\n';
  const offsets = [];
  for (let i = 1; i < objects.length; i++) {
    offsets[i] = out.length;
    out += `${i} 0 obj\n${objects[i]}\nendobj\n`;
  }
  const xref = out.length;
  out += `xref\n0 ${objects.length}\n0000000000 65535 f \n`;
  for (let i = 1; i < objects.length; i++) {
    out += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  }
  out += `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;

  const bytes = new Uint8Array(out.length);
  for (let i = 0; i < out.length; i++) bytes[i] = out.charCodeAt(i) & 0xff;
  return new Blob([bytes], { type: 'application/pdf' });
}
